### PR TITLE
Place selected keywords in URL of /TASKS and /CROWDS

### PR DESCRIPTION
**Pull request by davidsemakula**
Place selected keywords in URL of /TASKS and /CROWDS
so the selection can be bookmarked and shared

Fixes issue: https://github.com/mobbr/mobbr-frontend/issues/182

### CODE REVIEW

**Comment by patricksavalle** [comment]
Nice. I will ask our front-developers to check and merge! @handijk :)

**Comment by davidsemakula** [comment]
Great

**Comment by handijk** [comment]
@davidsemakula could you base your branch on develop next time? Master is in sync so it won't be a problem for now.

**Comment by davidsemakula** [comment]
OK will do

**Pull request merged**
